### ISSUE TITLE
README:  rawhtml format error

### ISSUE THREAD

**Issue by XmchxUp** [lryong/hugo-leetcode-dashboard#3]

**Comment by lryong** [comment]
@XmchxUp 这个问题有解决吗，可以贴下错误日志 @XmchxUp

**Comment by XmchxUp** [comment]
可能是解决了[PR](https://github.com/lryong/hugo-leetcode-dashboard/pull/4/commits/1a316f12b46fb5e9d2f78a74bacf75fa53e97e2d)，忘记了，太久远了。
