### ISSUE TITLE
too many file descriptors in select 

### ISSUE THREAD

**Issue by lyr-2000** [lryong/hugo-leetcode-dashboard#5]
![image](https://user-images.githubusercontent.com/46613910/167992537-c183e9f7-8d43-4110-a747-977311e07c0f.png)

是题解太多了？ 直接爆了吗？ 

😂

**Comment by lryong** [comment]
貌似是，可以看下是否能先手动解决~ @lyr-2000

**Comment by lryong** [comment]
看着是，这个问题已经解决吗 @lyr-2000

**Comment by lyr-2000** [comment]
解决了，又有新的问题， 解决的方法是 ，windows 环境下用一个&nbsp;Proactor&nbsp;的 eventloop ，大概是这样, 不过这个项目还有个新的问题，&nbsp; &nbsp;就是 字典那里中括号 取值会报 keyError, 因为 可能有些 题目类型或者什么的 代码里没有，然后字典取值就报错了。 目前大概遇到这2个问题。


参考：&nbsp;https://stackoverflow.com/questions/47675410/python-asyncio-aiohttp-valueerror-too-many-file-descriptors-in-select-on-win






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lryong/hugo-leetcode-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 凌晨0:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lryong/hugo-leetcode-dashboard] too many file descriptors in select  (Issue #5)





 
看着是，这个问题已经解决吗 @lyr-2000

**Comment by lryong** [comment]
@lyr-2000  是的， 感谢反馈。
对于提到的新问题， 自己在使用过程中也有遇到过。 语言类型的支持硬编码在代码里的， 个人还没有完全补全。
如果你有兴趣的话，可以 fix 并提一个 PR， 谢谢~

**Comment by lryong** [comment]
https://github.com/lryong/hugo-leetcode-dashboard/commit/d3ae5f6a93d05286a4b2294d4ae58a93851c8ccd 已经 fix 提到问题 @lyr-2000
